### ISSUE TITLE
fix: shorebird patch android fails with "No artifact found for architecture aarch64"

### ISSUE THREAD

**Issue by jonasbark** [shorebirdtech/shorebird#1191]
**Description**

Both builds were done on `ubuntu-latest` github runner.

```
Run shorebird patch android --force --flavor envtest
  shorebird patch android --force --flavor envtest
  shell: /usr/bin/sh -e ***0***
  env:
    JAVA_HOME_1[2](...#step:14:2).0.2_x64: /opt/hostedtoolcache/jdk/12.0.2/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/12.0.2/x64
    JAVA_HOME_12_0_2_X64: /opt/hostedtoolcache/jdk/12.0.2/x64
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-[3]...
    PUB_CACHE: /opt/hostedtoolcache/flutter/stable-3.13.1-x64/.pub-cache
    SHOREBIRD_TOKEN: ***
⠋ Fetching apps...
✓ Fetching apps (0.3s)
⠋ Building patch...
✓ Building patch (474.4s)
⠋ Detecting release version...
✓ Detected release version 3.13.2+327 (1.0s)
⠋ Fetching releases...
✓ Fetching releases (0.2s)
⠋ Fetching release artifacts...
✗ No artifact found for architecture aarch64 in release 6272 ([5](...#step:14:5)4ms)
```

The release for it was created one day before:

```
Run shorebird release android --force --flavor envtest
⠋ Building release...
✓ Building release (456.3s)
⠋ Fetching apps...
✓ Fetching apps (0.4s)
⠋ Detecting release version...
✓ Detecting release version (2.5s)
⠋ Fetching releases...
✓ Fetching releases (81ms)

🚀 Ready to create a new release!

📱 App: ... (live) (2a1896e6-828d-4df6-bd6f-b5ac426578e9)
🍧 Flavor: envtest
📦 Release Version: 3.[13](...).2+335
🕹️  Platform: android (arm64, arm32, x86_64)

⠋ Creating release...
✓ Creating release (0.2s)
⠋ Creating artifacts...
✓ Creating artifacts (5.8s)
⠋ Updating release status...
✓ Updating release status (76ms)

✅ Published Release!

Your next step is to upload the app bundle to the Play Store.
build/app/outputs/bundle/envtestRelease/app-envtest-release.aab
```

**Comment by JgomesAT** [comment]
I have the same error: withi the command flutter release works fine

Execution failed for task ':app:checkReleaseDuplicateClasses'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve io.flutter:armeabi_v7a_release:1.0.0-2371d9ab3129c719aa135ac04f7c34b1d0e4dbbe.
   
   Could not resolve io.flutter:arm64_v8a_release:1.0.0-2371d9ab3129c719aa135ac04f7c34b1d0e4dbbe.
     Required by:
         project :app
      > Could not resolve io.flutter:arm64_v8a_release:1.0.0-2371d9ab3129c719aa135ac04f7c34b1d0e4dbbe.
         > inconsistent module metadata found. Descriptor: io.flutter:arm64_v8a_release:1.0.0-401e07ae76c9e3d9ba1a427a92b9b89a2ba3cbae Errors: bad version: expected='1.0.0-2371d9ab3129c719aa135ac04f7c34b1d0e4dbbe' found='1.0.0-401e07ae76c9e3d9ba1a427a92b9b89a2ba3cbae'
   > Could not resolve io.flutter:x86_64_release:1.0.0-2371d9ab3129c719aa135ac04f7c34b1d0e4dbbe.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_64_release:1.0.0-2371d9ab3129c719aa135ac04f7c34b1d0e4dbbe.
         > inconsistent module metadata found. Descriptor: io.flutter:x86_64_release:1.0.0-401e07ae76c9e3d9ba1a427a92b9b89a2ba3cbae Errors: bad version: expected='1.0.0-2371d9ab3129c719aa135ac04f7c34b1d0e4dbbe' found='1.0.0-401e07ae76c9e3d9ba1a427a92b9b89a2ba3cbae'
   > Could not resolve io.flutter:flutter_embedding_release:1.0.0-2371d9ab3129c719aa135ac04f7c34b1d0e4dbbe.
     Required by:
         project :app > project :firebase_core
         project :app > project :flutter_local_notifications
         project :app > project :path_provider_android
         project :app > project :qr_code_scanner
         project :app > project :flutter_secure_storage
         project :app > project :shared_preferences_android
         project :app > project :share_plus
         project :app > project :uni_links
         project :app > project :firebase_messaging
         project :app > project :firebase_app_check
         project :app > project :firebase_crashlytics
         project :app > project :flutter_plugin_android_lifecycle
         project :app > project :freerasp
         project :app > project :sqflite
         project :app > project :url_launcher_android
         project :app > project :in_app_review
         project :app > project :google_maps_flutter_android
         project :app > project :rive_common
         project :app > project :firebase_performance
         project :app > project :flutter_native_splash
         project :app > project :firebase_dynamic_links
         project :app > project :webview_flutter_android
         project :app > project :pdfx
         project :app > project :firebase_analytics
         project :app > project :geocoding_android
         project :app > project :package_info_plus
         project :app > project :device_info_plus
         project :app > project :firebase_remote_config
         project :app > project :local_auth_android
      > Could not resolve io.flutter:flutter_embedding_release:1.0.0-2371d9ab3129c719aa135ac04f7c34b1d0e4dbbe.
         > inconsistent module metadata found. Descriptor: io.flutter:flutter_embedding_release:1.0.0-401e07ae76c9e3d9ba1a427a92b9b89a2ba3cbae Errors: bad version: expected='1.0.0-2371d9ab3129c719aa135ac04f7c34b1d0e4dbbe' found='1.0.0-401e07ae76c9e3d9ba1a427a92b9b89a2ba3cbae'

**Comment by eseidel** [comment]
Apologies, we accidentally pushed some bad artifacts to our server last night as part of migrating our infrastructure.  We've now fixed the issue and you should be able to build again cleanly. Sorry for any inconvenience!
https://github.com/shorebirdtech/shorebird/issues/1192

Please let us know if it's not resolved for you now.

**Comment by jonasbark** [comment]
@eseidel still not resolved. Release was yesterday, attempt to patch was today:

```
2023-09-02T06:59:16.6829927Z ##[group]Run shorebird patch android --force --flavor envtest
2023-09-02T06:59:16.6924238Z ##[endgroup]
2023-09-02T06:59:19.9845562Z ⠋ Fetching apps...[2K
2023-09-02T06:59:19.9846775Z ✓ Fetching apps (0.5s)
2023-09-02T07:09:11.7926765Z ⠋ Building patch...[2K
2023-09-02T07:09:11.7928029Z ✓ Building patch (591.8s)
2023-09-02T07:09:12.9542182Z ⠋ Detecting release version...[2K
2023-09-02T07:09:12.9612275Z ✓ Detected release version 3.13.3+327 (1.0s)
2023-09-02T07:09:13.0020260Z ⠋ Fetching releases...[2K
2023-09-02T07:09:13.0021360Z ✓ Fetching releases (0.2s)
2023-09-02T07:09:13.0939615Z ⠋ Fetching release artifacts...[2K
2023-09-02T07:09:13.0939615Z ⠋ Fetching release artifacts...[2K
2023-09-02T07:09:13.0941801Z ✗ No artifact found for architecture aarch64 in release 6689 (87ms)

```

**Comment by JgomesAT** [comment]
It's working now

**Comment by jonasbark** [comment]
Tried it again, still fails.

**Comment by eseidel** [comment]
Ah, sorry, it appears we crossed bugs here. It looks like Jgnome's issue (which was https://github.com/shorebirdtech/shorebird/issues/1192).  Reopening and hiding earlier comments.

**Comment by eseidel** [comment]
Looking at our database for release_version='3.13.3+327', app_id='2a1896e6-828d-4df6-bd6f-b5ac426578e9', that's id 
6689 (as the log correctly stated).

It is correct, that there is only "arm" associated with that release, not "aarch64".  Perhaps the original creation of that release failed?  The console should also only show you `arm` (e.g. arm32) for that release:

https://console.shorebird.dev/apps/2a1896e6-828d-4df6-bd6f-b5ac426578e9/releases/6689
(That link will only work for you, even I can't see it currently -- we don't have any way to masquerade as users in our console yet.)

I believe it is possible to update a release with new artifacts if you believe you can recreate the exact release version from sources.  But currently with the data in Shorebird's server it is not possible for us to patch that release (we don't know what the base revision for arm64 looks like).

**Comment by jonasbark** [comment]
I double-checked the version numbers that shorebird patch used and these were indeed wrong. It attempted to use artifacts from an iOS-only version (that you linked). So it failing does make sense.

Thanks for your support!
