### ISSUE TITLE
fix: shorebird with media_kit

### ISSUE THREAD

**Issue by majusss** [shorebirdtech/shorebird#3243]
App ID: 1c384681-654a-428a-a3b2-84b4b0352d13

**Description**

SIGBUS crash (BUS_ADRALN) occurring only in Shorebird-built APKs when using media_kit package. The app crashes with "Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x2" during media player initialization. The crash is reproducible 100% of the time in Shorebird builds but never occurs in standard Flutter builds.

**Steps To Reproduce**

1. Create Flutter app using media_kit package for video playback
2. Build APK using `shorebird release android --artifact apk`
3. Install and launch the APK on device
4. Attempt to initialize or use media_kit player
5. App immediately crashes with SIGBUS error

**Expected Behavior**

Media_kit should initialize and function normally in Shorebird builds, same as in regular Flutter builds. The video/audio player should load without crashing.

**Screenshots**

Crash logs show:

```
F libc    : Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x2 in tid 18497 (jusss.purevideo), pid 18497 (jusss.purevideo)
F DEBUG   : esr: 000000008a000000 (PC Alignment Exception 0x22)
F DEBUG   : signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x0000000000000002 (read)
F DEBUG   : pc  0000000000000002  pst 0000000020001800
F DEBUG   : backtrace:
F DEBUG   :       #00 pc 0000000000000002  <unknown>
F DEBUG   :       #01 pc 0000000000010a98  [anon:FfiCallbackMetadata::TrampolinePage]
```

**Additional Context**

- **Repo**: majusss/purevideo
- **Platform**: Android (tested on Google Pixel device)
- **Flutter version**: 3.32.7
- **Shorebird version**: 1.6.52
- **media_kit version**: 1.2.0
- **Workaround attempted**: Disabled minification and shrinkResources - crash persists
- **Root cause**: The crash appears to be related to FFI callbacks in media_kit conflicting with Shorebird's patching mechanism. The FfiCallbackMetadata::TrampolinePage in the stack trace suggests memory alignment issues when Shorebird modifies FFI callback pointers.
- **Impact**: Makes media_kit completely unusable with Shorebird, blocking video/audio functionality in apps using Shorebird for code push updates.

This appears to be a fundamental compatibility issue between Shorebird's engine modifications and FFI-based packages like media_kit.

**Comment by eseidel** [comment]
Thank you!  It might be from https://developer.android.com/guide/practices/page-sizes and we might not have updated our page size constants.

**Comment by eseidel** [comment]
Nevermind, that looks like a null pointer crash.  It's crashing at 0x2.

**Comment by eseidel** [comment]
Love that this is open source!  That should make testing very easy, thank you! https://github.com/majusss/purevideo

**Comment by eseidel** [comment]
OK, looking now.

**Comment by eseidel** [comment]
Notes from building:
* key.properites is required.  Probably possible to make it optional in the gradle (I just commented out all signing configs for now).
* shorebird.yaml isn't checked in, but could be (there isn't anything secret in that file).
* Looks like media_kit also uses some deprecated APIs and likely needs an upgrade:
```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/Users/eseidel/.pub-cache/hosted/pub.dev/media_kit_video-1.3.0/android/src/main/java/com/alexmercerind/media_kit_video/VideoOutput.java:107: warning: [removal] onSurfaceDestroyed() in Callback has been deprecated and marked for removal
    public void onSurfaceDestroyed() {
                ^
/Users/eseidel/.pub-cache/hosted/pub.dev/media_kit_video-1.3.0/android/src/main/java/com/alexmercerind/media_kit_video/VideoOutput.java:97: warning: [removal] onSurfaceCreated() in Callback has been deprecated and marked for removal
    public void onSurfaceCreated() {
                ^
2 warnings
```

**Comment by eseidel** [comment]
I first tried on a Android SDK 32 emulator with 16kb page sizes enabled.  The app displays a warning when launching:

<img width="706" height="508" alt="Image" src="https://github.com/user-attachments/assets/5122c057-7991-400f-8438-9441ea5709ce" />
Not yet sure if that's Shorebird's fault or the app.  Testing a `flutter create` app I'm not able to get that warning.

**Comment by majusss** [comment]
> I first tried on a Android SDK 32 emulator with 16kb page sizes enabled.  The app displays a warning when launching:
> 
> <img width="706" height="508" alt="Image" src="https://github.com/user-attachments/assets/5122c057-7991-400f-8438-9441ea5709ce" />
> Not yet sure if that's Shorebird's fault or the app.  Testing a `flutter create` app I'm not able to get that warning.

I think I need to read about this

**Comment by eseidel** [comment]
Hmm, when I use Android's verification tool I don't see any issues:

https://cs.android.com/android/platform/superproject/main/+/main:system/extras/tools/check_elf_alignment.sh

```
./check_elf_alignment.sh build/app/outputs/flutter-apk/app-release.apk

Recursively analyzing build/app/outputs/flutter-apk/app-release.apk

=== APK zip-alignment ===
 1503140 lib/arm64-v8a/libapp.so (OK - compressed)
 4532016 lib/arm64-v8a/libdatastore_shared_counter.so (OK - compressed)
 4534703 lib/arm64-v8a/libflutter.so (OK - compressed)
11663321 lib/arm64-v8a/libmedia_kit_native_event_loop.so (OK - compressed)
11828462 lib/arm64-v8a/libmediakitandroidhelper.so (OK - compressed)
11940625 lib/arm64-v8a/libmpv.so (OK - compressed)
Verification successful
=========================

=== ELF alignment ===
ELF Verification Successful
=====================
```

So I'm not sure why it showed a warning the first time.

**Comment by eseidel** [comment]
The warning dialog might be a red herring.  It's probably coming from how we generate apk files via bundletool as part of `shorebird preview`
https://developer.android.com/tools/bundletool

**Comment by eseidel** [comment]
Dusting off a Google Pixel in hopes of reproducing the crash.

**Comment by eseidel** [comment]
If you're able to reproduce locally, seeing the entire crash stack would help a lot.

**Comment by majusss** [comment]
> If you're able to reproduce locally, seeing the entire crash stack would help a lot.

It's interesting because Flutter doesn't show any logs, the app just closes

**Comment by majusss** [comment]
> Dusting off a Google Pixel in hopes of reproducing the crash.

media_kit works well on your build?

**Comment by eseidel** [comment]
> > If you're able to reproduce locally, seeing the entire crash stack would help a lot.
> 
> It's interesting because Flutter doesn't show any logs, the app just closes

I would expect there to be logs in `adb logcat` if the app closes.

**Comment by eseidel** [comment]
> > Dusting off a Google Pixel in hopes of reproducing the crash.
> 
> media_kit works well on your build?

I've only run in an emulator, which may not be sufficient to trigger the crash. 🤷

**Comment by majusss** [comment]
> > > If you're able to reproduce locally, seeing the entire crash stack would help a lot.
> > 
> > It's interesting because Flutter doesn't show any logs, the app just closes
> 
> I would expect there to be logs in `adb logcat` if the app closes.

```
07-22 17:33:49.618   595   733 D DisplayModeController: setDesiredMode 4619827812140078592 {mode={fps=120.00 Hz, modePtr={id=1, vsyncRate=120.00 Hz, peakRefreshRate=120.00 Hz}}, emitEvent=true, force=false}
07-22 17:33:49.624   975  1014 D CHRE    : @ 147458.079: Parsed nanoapp message from host: app ID 0x476f6f676c00103b endpoint 0x8005 msgType 1 payload size 7
07-22 17:33:49.626   599   720 D hwc-display: setActiveConfigWithConstraints:: PrimaryDisplay config(37) test(0)
07-22 17:33:49.626   599   720 I hwc-display: [PrimaryDisplay] setActiveConfigWithConstraints: config(37)
07-22 17:33:49.694  2156  2161 I deeptouch: I0000 00:00:1753198429.694394    2161 tf_lite_classifier.cc:413] Event stream classified as kNone
07-22 17:33:49.701   975  1014 D CHRE    : @ 147458.160: Parsed nanoapp message from host: app ID 0x476f6f676c00103b endpoint 0x8005 msgType 1 payload size 5
07-22 17:33:49.723 13538 13538 F libc    : Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x2 in tid 13538 (jusss.purevideo), pid 13538 (jusss.purevideo)
07-22 17:33:49.880 13714 13714 W crash_dump64: failed to attach to thread 13656: No such process
07-22 17:33:49.882 13714 13714 E crash_dump64: failed to interrupt 13656 to detach: No such process
07-22 17:33:49.882 13714 13714 W crash_dump64: failed to ptrace interrupt thread 13656: No such process
07-22 17:33:49.981 13714 13714 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstoneProto
07-22 17:33:49.984   742   742 I tombstoned: received crash request for pid 13538
07-22 17:33:49.986 13714 13714 I crash_dump64: performing dump of process 13538 (target tid = 13538)
07-22 17:33:50.378 13714 13714 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-22 17:33:50.378 13714 13714 F DEBUG   : Build fingerprint: 'google/shiba_beta/shiba:16/BP31.250610.004/13769805:user/release-keys'
07-22 17:33:50.378 13714 13714 F DEBUG   : Kernel Release: '6.1.134-android14-11-ga4b2a2c52a04-ab13615798'
07-22 17:33:50.378 13714 13714 F DEBUG   : Revision: 'MP1.0'
07-22 17:33:50.378 13714 13714 F DEBUG   : ABI: 'arm64'
07-22 17:33:50.378 13714 13714 F DEBUG   : Timestamp: 2025-07-22 17:33:50.016640824+0200
07-22 17:33:50.378 13714 13714 F DEBUG   : Process uptime: 27s
07-22 17:33:50.378 13714 13714 F DEBUG   : Executable: /system/bin/app_process64
07-22 17:33:50.378 13714 13714 F DEBUG   : Cmdline: io.github.majusss.purevideo
07-22 17:33:50.378 13714 13714 F DEBUG   : pid: 13538, tid: 13538, name: jusss.purevideo  >>> io.github.majusss.purevideo <<<
07-22 17:33:50.378 13714 13714 F DEBUG   : uid: 10388
07-22 17:33:50.378 13714 13714 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
07-22 17:33:50.378 13714 13714 F DEBUG   : pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
07-22 17:33:50.378 13714 13714 F DEBUG   : esr: 000000008a000000 (PC Alignment Exception 0x22)
07-22 17:33:50.378 13714 13714 F DEBUG   : signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x0000000000000002 (read)
07-22 17:33:50.378 13714 13714 F DEBUG   :     x0  b4000072113d3680  x1  0000007177480b34  x2  b4000072113d3680  x3  b4000072113d3680
07-22 17:33:50.378 13714 13714 F DEBUG   :     x4  0000006f00009da1  x5  0000006f002c0081  x6  0000006f002c5931  x7  0000006f002dd1f1
07-22 17:33:50.378 13714 13714 F DEBUG   :     x8  0000000000000000  x9  00000070ce137a2c  x10 0000000000000002  x11 b4000071e13532c0
07-22 17:33:50.378 13714 13714 F DEBUG   :     x12 0000000000000002  x13 ffffff90fdcc80e7  x14 0000000000837780  x15 0000007ff9276140
07-22 17:33:50.378 13714 13714 F DEBUG   :     x16 00000070ddef3198  x17 0000007413ee0040  x18 0000007451e18000  x19 b4000072113d3730
07-22 17:33:50.378 13714 13714 F DEBUG   :     x20 0000007177480b34  x21 b4000072113d3680  x22 b4000072113d3680  x23 b4000071a134d030
07-22 17:33:50.378 13714 13714 F DEBUG   :     x24 0000006f00008081  x25 0000007ff8a9a000  x26 b40000725143a240  x27 0000006f00880080
07-22 17:33:50.378 13714 13714 F DEBUG   :     x28 000000080000006f  x29 0000007ff9276150
07-22 17:33:50.378 13714 13714 F DEBUG   :     lr  0000007177490a9c  sp  0000007ff9276140  pc  0000000000000002  pst 0000000020001800
07-22 17:33:50.378 13714 13714 F DEBUG   :     esr 000000008a000000
07-22 17:33:50.378 13714 13714 F DEBUG   : 2 total frames
07-22 17:33:50.378 13714 13714 F DEBUG   : backtrace:
07-22 17:33:50.378 13714 13714 F DEBUG   :       #00 pc 0000000000000002  <unknown>
07-22 17:33:50.378 13714 13714 F DEBUG   :       #01 pc 0000000000010a98  [anon:FfiCallbackMetadata::TrampolinePage]
07-22 17:33:50.423   742   742 E tombstoned: Tombstone written to: tombstone_09
07-22 17:33:50.424  1490 13719 I DropBoxManagerService: add tag=data_app_native_crash isTagEnabled=true flags=0x2
07-22 17:33:50.426  1490 13717 W ActivityTaskManager:   Force finishing activity io.github.majusss.purevideo/.MainActivity
07-22 17:33:50.427  1490 13717 W TransitionChain: Combining AR.finish-force-crash into #2089(CLOSE|R|0x10) from finishTopCrash
07-22 17:33:50.430  2170  2193 V WindowManagerShell: Transition requested (#2089): android.os.BinderProxy@ced6f68 TransitionRequestInfo { type = CLOSE, triggerTask = TaskInfo{userId=0 taskId=2998 effectiveUid=10388 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.github.majusss.purevideo/.MainActivity } baseActivity=ComponentInfo{io.github.majusss.purevideo/io.github.majusss.purevideo.MainActivity} topActivity=ComponentInfo{io.github.majusss.purevideo/io.github.majusss.purevideo.MainActivity} origActivity=null realActivity=ComponentInfo{io.github.majusss.purevideo/io.github.majusss.purevideo.MainActivity} numActivities=1 lastActiveTime=147413808 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.os.BinderProxy@c127d88} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 0 - 0, 0) topActivityInfo=ActivityInfo{b7a4f81 io.github.majusss.purevideo.MainActivity} launchCookies=[android.os.BinderProxy@7056346] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=true isVisibleRequested=true isTopActivityNoDisplay=false isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false isActivityStackTransparent=false lastNonFullscreenBounds=Rect(276, 694 - 804, 1774) capturedLink=null capturedLinkTimestamp=0 requestedVisibleTypes=-9 topActivityRequestOpenInBrowserEducationTimestamp=0 appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false eligibleForLetterboxEducation= false isLetterboxEducationEnabled= false isLetterboxDoubleTapEnabled= false eligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 topActivityAppBounds=Rect(0, 0 - 1080, 2400) isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false hasMinAspectRatioOverride=false topActivityLetterboxBounds=null cameraCompatTaskInfo=CameraCompatTaskInfo { freeformCameraCompatMode=inactiveundefined} topNonResizableActivityAspectRatio=-1.0} topActivityMainWindowFrame=null isAppBubble=false}, pipChange = null, remoteTransition = null, displayChange = null, flags = 16, debugId = 2089 }
07-22 17:33:50.433   595   857 I libbinder.BpBinder: onLastStrongRef automatically unlinking death recipients: 
07-22 17:33:50.437  1490 13717 V WindowManager: Defer transition id=2089 for TaskFragmentTransaction=android.os.Binder@f25c89
07-22 17:33:50.437  1490 13717 V WindowManager: deferTransitionReady deferReadyDepth=1 stack=com.android.server.wm.TransitionController.deferTransitionReady:1014 com.android.server.wm.TaskFragmentOrganizerController$TaskFragmentOrganizerState.dispatchTransaction:508 com.android.server.wm.TaskFragmentOrganizerController.dispatchPendingEvents:1250 com.android.server.wm.TaskFragmentOrganizerController.dispatchPendingEvents:1219 com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace:808 
07-22 17:33:50.452  1490  3664 V WindowManager: Continue transition id=2089 for TaskFragmentTransaction=android.os.Binder@f25c89
07-22 17:33:50.452  1490  3664 V WindowManager: continueTransitionReady deferReadyDepth=0 stack=com.android.server.wm.TransitionController.continueTransitionReady:1023 com.android.server.wm.TaskFragmentOrganizerController$TaskFragmentOrganizerState.onTransactionFinished:537 com.android.server.wm.TaskFragmentOrganizerController.onTransactionHandled:731 android.window.ITaskFragmentOrganizerController$Stub.onTransact:225 android.os.Binder.execTransactInternal:1441 
07-22 17:33:50.476  1490  1982 I DropBoxManagerService: add tag=SYSTEM_TOMBSTONE_PROTO_WITH_HEADERS isTagEnabled=true flags=0x4
07-22 17:33:50.608  1490  1982 I BootReceiver: Copying /data/tombstones/tombstone_09 to DropBox (SYSTEM_TOMBSTONE)
07-22 17:33:50.609  1490  1982 I DropBoxManagerService: add tag=SYSTEM_TOMBSTONE isTagEnabled=true flags=0x6
07-22 17:33:50.627  1490  2488 I ActivityManager: Process io.github.majusss.purevideo (pid 13538) has died: fg  TOP 
07-22 17:33:50.628  1490  4936 I WindowManager: WIN DEATH: Window{98c025e u0 io.github.majusss.purevideo/io.github.majusss.purevideo.MainActivity}
07-22 17:33:50.629   699   699 W powerhal-libperfmgr: sched_setattr failed for thread 13609, err=3
07-22 17:33:50.629   699   699 W powerhal-libperfmgr: sched_setattr failed for thread 13610, err=3
07-22 17:33:50.629   699   699 W powerhal-libperfmgr: sched_setattr failed for thread 13564, err=3
07-22 17:33:50.638   952   952 I Zygote  : Process 13538 exited due to signal 7 (Bus error)
07-22 17:33:50.641  1490  2488 W TransitionChain: Combining appDied into #2089(CLOSE|R|0x10) from finishTopCrash
07-22 17:33:50.651  2457  2457 D ViewRootImpl: Skipping stats log for color mode
07-22 17:33:50.652  2457  2457 D BaseActivity: Launcher flags updated: [state_started] +[state_started]
07-22 17:33:50.652  2457  2457 D BaseActivity: Launcher flags updated: [state_started|state_resumed|state_user_active] +[state_resumed|state_user_active]
07-22 17:33:50.653  2457  2457 D BaseActivity: Launcher flags updated: [state_started|state_resumed|state_deferred_resumed|state_user_active] +[state_deferred_resumed]
07-22 17:33:50.653  2457  2457 D StatsLog: LAUNCHER_ONRESUME
07-22 17:33:50.653  1490  1593 W ActivityManager: setHasOverlayUi called on unknown pid: 13538
07-22 17:33:50.656  1490  3658 I ImeTracker: io.github.majusss.purevideo:7f70fdd2: onRequestHide at ORIGIN_SERVER reason HIDE_REMOVE_CLIENT fromUser false
07-22 17:33:50.656  1490  3658 I ImeTracker: io.github.majusss.purevideo:7f70fdd2: onCancelled at PHASE_SERVER_SHOULD_HIDE
07-22 17:33:50.658  2457  2457 D NexusLauncherModelDelegate: notifySmartspaceEvent: SmartspaceTargetEvent{mSmartspaceTarget=null, mSmartspaceActionId='null', mEventType=6}
07-22 17:33:50.662  2457  2559 D QuickstepModelDelegate: notifyAppTargetEvent action=1 launchLocation=
07-22 17:33:50.670  2170  2619 D WallpaperService: onVisibilityChanged(true): com.android.systemui.wallpapers.ImageWallpaper$CanvasEngine@e95ce
07-22 17:33:50.674  2457  2457 D BaseDepthController: setSurface:
07-22 17:33:50.674  2457  2457 D BaseDepthController:   mWaitingOnSurfaceValidity: false
07-22 17:33:50.674  2457  2457 D BaseDepthController:   mBaseSurface: Surface(name=com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity)/@0xecad98a
07-22 17:33:50.674  2457  2457 V BaseDepthController: Applying blur: 79 to Surface(name=com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity)/@0xecad98a
07-22 17:33:50.661  1490  1607 I libprocessgroup: Removed cgroup /sys/fs/cgroup/apps/uid_10388/pid_13538
07-22 17:33:50.697  1490  2124 D BackgroundInstallControlService: Package event received: 0
07-22 17:33:50.698  1490  2124 D BackgroundInstallControlService: Package event received: 0
07-22 17:33:50.698  1490  2124 D BackgroundInstallControlService: Package event received: 0
07-22 17:33:50.712  2457  2457 I NotificationListener: Handling notification state refresh for com.facebook.orca#0
07-22 17:33:50.712  2457  2457 I NotificationListener: Handling notification state refresh for ch.protonmail.android#0
07-22 17:33:50.713  1490  2066 D InetDiagMessage: Destroyed 0 sockets, proto=IPPROTO_TCP, family=AF_INET, states=14
07-22 17:33:50.715  1490  2066 D InetDiagMessage: Destroyed 0 sockets, proto=IPPROTO_TCP, family=AF_INET6, states=14
07-22 17:33:50.715  1490  2066 D InetDiagMessage: Destroyed live tcp sockets for uids={10388} in 14ms
07-22 17:33:50.718  1490  2066 D InetDiagMessage: Destroyed 0 sockets, proto=IPPROTO_TCP, family=AF_INET, states=14
07-22 17:33:50.723  1490  2066 D InetDiagMessage: Destroyed 0 sockets, proto=IPPROTO_TCP, family=AF_INET6, states=14
07-22 17:33:50.723  1490  2066 D InetDiagMessage: Destroyed live tcp sockets for uids={20388} in 8ms
07-22 17:33:50.727  2170  2768 V WindowManagerShell: onTransitionReady(transaction=6399501457220)
07-22 17:33:50.727  2170  2193 V WindowManagerShell: onTransitionReady (#2089) android.os.BinderProxy@ced6f68: {id=2089 t=CLOSE f=0x10 trk=0 r=[0@Point(0, 0)] c=[
07-22 17:33:50.727  2170  2193 V WindowManagerShell:         {m=TO_FRONT f=SHOW_WALLPAPER|MOVE_TO_TOP leash=Surface(name=Task=1)/@0x6135826 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) epz=Point(1080, 2400) d=0 taskParent=-1 winMode=1},
07-22 17:33:50.727  2170  2193 V WindowManagerShell:         {m=CLOSE f=NONE leash=Surface(name=Task=2998)/@0xe7c4c67 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) epz=Point(1080, 2400) d=0 taskParent=-1 winMode=1},
07-22 17:33:50.727  2170  2193 V WindowManagerShell:         {m=TO_FRONT f=IS_WALLPAPER leash=Surface(name=WallpaperWindowToken{e70560a})/@0x8de1a14 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) epz=Point(1080, 2400) d=0}
07-22 17:33:50.727  2170  2193 V WindowManagerShell:     ]}
07-22 17:33:50.728  2170  2193 V WindowManagerShell: Playing animation for (#2089) android.os.BinderProxy@ced6f68@0
07-22 17:33:50.728  2170  2193 V ShellRecents: RecentsTransitionHandler.startAnimation: no controller found
07-22 17:33:50.729  2170  2193 V WindowManagerShell: Transition doesn't have explicit remote, search filters for match for {id=2089 t=CLOSE f=0x10 trk=0 r=[0@Point(0, 0)] c=[{m=TO_FRONT f=SHOW_WALLPAPER|MOVE_TO_TOP leash=Surface(name=Task=1)/@0x6135826 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) epz=Point(1080, 2400) d=0 taskParent=-1 winMode=1},{m=CLOSE f=NONE leash=Surface(name=Task=2998)/@0xe7c4c67 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) epz=Point(1080, 2400) d=0 taskParent=-1 winMode=1},{m=TO_FRONT f=IS_WALLPAPER leash=Surface(name=WallpaperWindowToken{e70560a})/@0x8de1a14 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) epz=Point(1080, 2400) d=0}]}
07-22 17:33:50.729  2170  2193 V WindowManagerShell:  Checking filter Pair{{types=[] flags=0x0] notFlags=0x0 checks=[{atype=undefined independent=true modes=[CLOSE,TO_BACK] flags=IN_TASK_WITH_EMBEDDED_ACTIVITY mustBeTask=false order=ANY topActivity=null launchCookie=null taskFragmentToken=android.os.BinderProxy@6071c8 windowingMode=undefined}]} RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@46b9261, appThread = android.app.IApplicationThread$Stub$Proxy@6d1186, debugName = overlayBackTransition }}
07-22 17:33:50.729  2170  2193 V WindowManagerShell:  Checking filter Pair{{types=[] flags=0x0] notFlags=0x0 checks=[{atype=dream independent=true modes=[OPEN,TO_FRONT] flags=NONE mustBeTask=false order=ANY topActivity=null launchCookie=null windowingMode=undefined},{atype=home independent=true modes=[CLOSE,TO_BACK] flags=NONE mustBeTask=false order=ANY topActivity=null launchCookie=null windowingMode=undefined}]} RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@d6b7a47, appThread = android.app.IApplicationThread$Stub$Proxy@feee274, debugName = LauncherToDream }}
07-22 17:33:50.729  2170  2193 V WindowManagerShell:  Checking filter Pair{{types=[] flags=0x0] notFlags=0x100 checks=[{atype=home independent=true modes=[OPEN,TO_FRONT] flags=NONE mustBeTask=false order=TOP topActivity=ComponentInfo{com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity} launchCookie=null windowingMode=undefined},{atype=standard independent=true modes=[CLOSE,TO_BACK] flags=NONE mustBeTask=false order=ANY topActivity=null launchCookie=null windowingMode=undefined},{NOT atype=undefined independent=true modes=[] flags=NONE mustBeTask=true order=ANY topActivity=null launchCookie=null customAnim=true windowingMode=undefined}]} RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@b6df39d, appThread = android.app.IApplicationThread$Stub$Proxy@678c012, debugName = QuickstepLaunchHome }}
07-22 17:33:50.730  2170  2193 D RemoteTransitionHandler: Found filterPair{{types=[] flags=0x0] notFlags=0x100 checks=[{atype=home independent=true modes=[OPEN,TO_FRONT] flags=NONE mustBeTask=false order=TOP topActivity=ComponentInfo{com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity} launchCookie=null windowingMode=undefined},{atype=standard independent=true modes=[CLOSE,TO_BACK] flags=NONE mustBeTask=false order=ANY topActivity=null launchCookie=null windowingMode=undefined},{NOT atype=undefined independent=true modes=[] flags=NONE mustBeTask=true order=ANY topActivity=null launchCookie=null customAnim=true windowingMode=undefined}]} RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@b6df39d, appThread = android.app.IApplicationThread$Stub$Proxy@678c012, debugName = QuickstepLaunchHome }}
07-22 17:33:50.730  2170  2193 V WindowManagerShell:  Delegate animation for (#2089) to RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@b6df39d, appThread = android.app.IApplicationThread$Stub$Proxy@678c012, debugName = QuickstepLaunchHome }
07-22 17:33:50.738  1490  1590 V WindowManager: Sent Transition (#2089) createdAt=07-22 17:33:50.426 via request=TransitionRequestInfo { type = CLOSE, triggerTask = TaskInfo{userId=0 taskId=2998 effectiveUid=10388 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.github.majusss.purevideo/.MainActivity } baseActivity=ComponentInfo{io.github.majusss.purevideo/io.github.majusss.purevideo.MainActivity} topActivity=ComponentInfo{io.github.majusss.purevideo/io.github.majusss.purevideo.MainActivity} origActivity=null realActivity=ComponentInfo{io.github.majusss.purevideo/io.github.majusss.purevideo.MainActivity} numActivities=1 lastActiveTime=147413808 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{RemoteToken{82dec76 Task{7ffadab #2998 type=standard I=io.github.majusss.purevideo/.MainActivity}}} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 0 - 0, 0) topActivityInfo=ActivityInfo{2ddd277 io.github.majusss.purevideo.MainActivity} launchCookies=[android.os.BinderProxy@d9d0ee4] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=true isVisibleRequested=true isTopActivityNoDisplay=false isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false isActivityStackTransparent=false lastNonFullscreenBounds=Rect(276, 694 - 804, 1774) capturedLink=null capturedLinkTimestamp=0 requestedVisibleTypes=-9 topActivityRequestOpenInBrowserEducationTimestamp=0 appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false eligibleForLetterboxEducation= false isLetterboxEducationEnabled= false isLetterboxDoubleTapEnabled= false eligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 topActivityAppBounds=Rect(0, 0 - 1080, 2400) isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false hasMinAspectRatioOverride=false topActivityLetterboxBounds=null cameraCompatTaskInfo=CameraCompatTaskInfo { freeformCameraCompatMode=inactiveundefined} topNonResizableActivityAspectRatio=-1.0} topActivityMainWindowFrame=null isAppBubble=false}, pipChange = null, remoteTransition = null, displayChange = null, flags = 16, debugId = 2089 }
07-22 17:33:50.738  1490  1590 V WindowManager:     startWCT=WindowContainerTransaction { changes= {} hops= [] errorCallbackToken=null taskFragmentOrganizer=null }
07-22 17:33:50.738  1490  1590 V WindowManager:     info={id=2089 t=CLOSE f=0x10 trk=0 r=[0@Point(0, 0)] c=[
07-22 17:33:50.738  1490  1590 V WindowManager:         {WCT{RemoteToken{40f55b3 Task{1f98b5c #1 type=home}}} m=TO_FRONT f=SHOW_WALLPAPER|MOVE_TO_TOP leash=Surface(name=Task=1)/@0x71462cd sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) epz=Point(1080, 2400) d=0 taskParent=-1 winMode=1},
07-22 17:33:50.738  1490  1590 V WindowManager:         {WCT{RemoteToken{82dec76 Task{7ffadab #2998 type=standard I=io.github.majusss.purevideo/.MainActivity}}} m=CLOSE f=NONE leash=Surface(name=Task=2998)/@0xf7f7faa sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) epz=Point(1080, 2400) d=0 taskParent=-1 winMode=1},
07-22 17:33:50.738  1490  1590 V WindowManager:         {m=TO_FRONT f=IS_WALLPAPER leash=Surface(name=WallpaperWindowToken{e70560a})/@0x91021a5 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) epz=Point(1080, 2400) d=0}
07-22 17:33:50.738  1490  1590 V WindowManager:     ]}
07-22 17:33:50.743  2457  2457 D b/311077782: LauncherAnimationRunner.setAnimation
07-22 17:33:50.747  2457  2457 D ImeBackDispatcher: switch root view (mImeCallbacks.size=0)
07-22 17:33:50.747  2457  2457 D BaseActivity: Launcher flags updated: [state_started|state_resumed|state_deferred_resumed|state_window_focused|state_user_active] +[state_window_focused]
07-22 17:33:50.750  2170  2193 V WindowManagerShell:  animated by com.android.wm.shell.transition.RemoteTransitionHandler@759defd
07-22 17:33:50.750  2170  2193 D Bubbles : onLocusVisibilityChanged=Overview|DISABLED visible=true taskId=1
07-22 17:33:50.761  1490  1593 W ProcessStats: Tracking association SourceState{37349b4 system/1000 ImpBg #213486} whose proc state 6 is better than process ProcessState{f659848 com.google.android.inputmethod.latin/10183 pkg=com.google.android.inputmethod.latin} proc state 14 (15 skipped)
07-22 17:33:50.766  1490  2028 I ImeTracker: com.google.android.apps.nexuslauncher:93ca5f10: onRequestShow at ORIGIN_SERVER reason ATTACH_NEW_INPUT fromUser false
07-22 17:33:50.773  1490  2028 I ImeTracker: com.google.android.apps.nexuslauncher:376e527e: onRequestShow at ORIGIN_SERVER reason SHOW_RESTORE_IME_VISIBILITY fromUser false
07-22 17:33:50.773  1490  2124 D BackgroundInstallControlService: Package event received: 0
07-22 17:33:50.775   699   699 W powerhal-libperfmgr: Sess(5741), cannot resume, already active
07-22 17:33:50.778  1490  3658 I ImeTracker: system_server:5a02322d: onRequestHide at ORIGIN_SERVER reason IME_REQUESTED_CHANGED_LISTENER fromUser false
07-22 17:33:50.779  2457  2457 D InsetsController: show(ime())
07-22 17:33:50.779  2457  2457 D ImeBackDispatcher: Undo preliminary clear (mImeCallbacks.size=0)
07-22 17:33:50.780  2457  2457 D InsetsController: Setting requestedVisibleTypes to -1 (was -9)
07-22 17:33:50.790  1490  2124 D BackgroundInstallControlService: Package event received: 0
07-22 17:33:50.792  1490  1590 D HintManagerService: Sent cleanup message for uid 10293
07-22 17:33:50.796  1490  2028 W InputMethodManagerService: Delegator package does not match. Ignoring startStylusHandwriting
07-22 17:33:50.797   699   699 W powerhal-libperfmgr: Sess(5741), cannot resume, already active
07-22 17:33:50.799  2457  2457 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-22 17:33:50.804  2457  2457 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-22 17:33:50.806 27140 27140 D ImeBackDispatcher: Send callback registration id=5558475 priority=0
07-22 17:33:50.807  2457  2457 D ImeBackDispatcher: Register received callback id=5558475 priority=0
07-22 17:33:50.807  2457  2457 D WindowOnBackDispatcher: setTopOnBackInvokedCallback (unwrapped): ImeOnBackInvokedCallback@5558475 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@875f57d
07-22 17:33:50.810  2457  2457 D ImeBackDispatcher: Unregister received callback id=5558475
07-22 17:33:50.810  2457  2457 D WindowOnBackDispatcher: setTopOnBackInvokedCallback (unwrapped): com.android.launcher3.uioverrides.QuickstepLauncher$3@6e68b2c
07-22 17:33:50.812  1490  2487 D CoreBackPreview: Window{1c2111d u0 com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@6ef7efa, mPriority=0, mIsAnimationCallback=true, mOverrideBehavior=0}
07-22 17:33:50.810 27140 27140 D ImeBackDispatcher: Send callback unregistration id=5558475
07-22 17:33:50.812 27140 27140 I ImeTracker: system_server:5a02322d: onHidden
07-22 17:33:50.813  1490  2874 D ImeInsetsSourceProvider: showImePostLayout aborted, serverVisible: false, frozen: false, mWin is: non-null, isDrawn: false, mGivenInsetsPending: false, imeLayeringTarget: Window{1c2111d u0 com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity}, controlTarget: Window{1c2111d u0 com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity}
07-22 17:33:50.813  1490  2874 D ImeInsetsSourceProvider: controlTarget == DisplayContent.imeControlTarget: true, hasPendingControls: false, leash is: non-null
07-22 17:33:50.814  1490  2874 I ImeTracker: com.google.android.apps.nexuslauncher:93ca5f10: onFailed at PHASE_WM_ABORT_SHOW_IME_POST_LAYOUT
07-22 17:33:50.815  1490  2487 D CoreBackPreview: Window{1c2111d u0 com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@c056cab, mPriority=0, mIsAnimationCallback=true, mOverrideBehavior=0}
07-22 17:33:50.820  2170  2193 D WindowManagerShell: onKeepClearAreasChanged: restricted={}, unrestricted={Rect(0, 1563 - 1080, 2400)}
07-22 17:33:50.838  2170  2193 D WindowManagerShell: onKeepClearAreasChanged: restricted={}, unrestricted={Rect(0, 1447 - 1080, 2400)}
07-22 17:33:50.864 27140 27140 D FullKeyboardServiceDelegate: onTrimMemory called with level: 20
07-22 17:33:50.864  3597  4190 I AiAiEcho: Predicting[6]: { Feature:1, creation:2025-07-22T19:00:00Z, expiry:2025-07-22T19:00:00Z, isExpired: true}, { Feature:1, creation:2025-07-22T17:00:00Z, expiry:2025-07-22T17:00:00Z, isExpired: true}, { Feature:1, creation:2025-07-22T18:00:00Z, expiry:2025-07-22T18:00:00Z, isExpired: true}, { Feature:1, creation:2025-07-22T15:00:00Z, expiry:2025-07-22T16:00:00Z, isExpired: false}, { Feature:1, creation:2025-07-22T16:00:00Z, expiry:2025-07-22T16:00:00Z, isExpired: true}, { Feature:1, creation:2025-07-22T14:00:00Z, expiry:2025-07-22T15:00:00Z, isExpired: true} [CONTEXT sampling_count=5 ]
07-22 17:33:50.871  3597  4190 I AiAiEcho: EchoTargets: Feature:1
07-22 17:33:50.871  3597  4190 I AiAiEcho: Filtered by AiAi flag check: 
07-22 17:33:50.871  3597  4190 I AiAiEcho: [CONTEXT ratelimit_period="10 SECONDS" ]
07-22 17:33:50.872  1428  1739 I twoshay.TouchContextService: Got new packet! ContextPacket{orientation: PORTRAIT, audioMode: NORMAL, adaptiveTouchSensitivity: OFF, screenProtectorMode: OFF, imeState: ImeState{displayId: 0, visible: true, top: 0, left: 0, bottom: 0, right: 0}, audioDeviceInfo: TYPE_UNKNOWN}
07-22 17:33:50.872  3597  4190 I AiAiEcho: #weatherTwiddler: Weather removes SubtitleSupplementalItem in surface: home [CONTEXT ratelimit_period="10 SECONDS" ]
07-22 17:33:50.872  3597  4190 I AiAiEcho: #remoteViewsTwiddler: feature disabled.
07-22 17:33:50.873  1428  1739 I twoshay.TouchContextService: Got new packet! ContextPacket{orientation: PORTRAIT, audioMode: NORMAL, adaptiveTouchSensitivity: OFF, screenProtectorMode: OFF, imeState: ImeState{displayId: 0, visible: true, top: 1447, left: 0, bottom: 2400, right: 1080}, audioDeviceInfo: TYPE_UNKNOWN}
07-22 17:33:50.878  2457  2457 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-22 17:33:50.881 27140 27140 D ImeBackDispatcher: Send callback registration id=5558475 priority=0
07-22 17:33:50.881  3597  4190 I AiAiEcho: #postPredictionTargets: Sending updates to UISurface home with targets# 1 (types=[1])
07-22 17:33:50.882  2457  2457 D ImeBackDispatcher: Register received callback id=5558475 priority=0
07-22 17:33:50.882  2457  2457 D WindowOnBackDispatcher: setTopOnBackInvokedCallback (unwrapped): ImeOnBackInvokedCallback@5558475 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@70598b3
07-22 17:33:50.890  1490  2025 D CoreBackPreview: Window{1c2111d u0 com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@22690c6, mPriority=0, mIsAnimationCallback=true, mOverrideBehavior=0}
07-22 17:33:50.894  1490  1945 I ImeTracker: com.google.android.apps.nexuslauncher:376e527e: onCancelled at PHASE_WM_POST_LAYOUT_NOTIFY_CONTROLS_CHANGED
07-22 17:33:50.899  1490  1594 I ImeTracker: system_server:1a1d981c: onRequestShow at ORIGIN_SERVER reason CONTROLS_CHANGED fromUser false
07-22 17:33:50.930  1490  1593 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{55976954 u0 io.github.majusss.purevideo/.MainActivity t2998 f} isExiting}
07-22 17:33:51.139  2318  2521 D ImpulseConnection: timeout didn't happen: com.google.android.apps.turbo
07-22 17:33:51.196  2170  2193 V WindowManagerShell: Transition animation finished (aborted=false), notifying core (#2089) android.os.BinderProxy@ced6f68@0
07-22 17:33:51.201  2457  2457 D SsBaseTemplateCard: No text view can be set up
07-22 17:33:51.202  2457  2457 I SsBaseTemplateCard: setFormattedContentDescription: text=27°C, iconDescription=Partly cloudy, contentDescription=Partly cloudy, 27°C
07-22 17:33:51.202  2457  2457 D SsBaseTemplateCard: Passed-in item info is null
07-22 17:33:51.202  2457  2457 D SsBaseTemplateCard: Passed-in item info is null
07-22 17:33:51.202  2457  2457 I SsBaseTemplateCard: Secondary card pane is null
07-22 17:33:51.204  1490  3658 E libbinder.IPCThreadState: Binder transaction failure. id: 65370817, BR_*: 29189, error: -22 (Invalid argument)
07-22 17:33:51.204  1490  3658 W ActivityManager: pid 1490 system sent binder code 7 with flags 1 and got error -32
07-22 17:33:51.204  1490  1590 V WindowManager: Finish Transition (#2089): created at 07-22 17:33:50.426 collect-started=0.225ms request-sent=0.611ms started=13.547ms ready=222.812ms sent=292.777ms commit=23.201ms finished=776.671ms
07-22 17:33:51.205  1490  3658 W WindowManager: Exception thrown during dispatchAppVisibility Window{98c025e u0 io.github.majusss.purevideo/io.github.majusss.purevideo.MainActivity EXITING}
07-22 17:33:51.205  1490  3658 W WindowManager: android.os.DeadObjectException
07-22 17:33:51.205  1490  3658 W WindowManager:         at android.os.BinderProxy.transactNative(Native Method)
07-22 17:33:51.205  1490  3658 W WindowManager:         at android.os.BinderProxy.transact(BinderProxy.java:592)
07-22 17:33:51.205  1490  3658 W WindowManager:         at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:538)
07-22 17:33:51.205  1490  3658 W WindowManager:         at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3183)
07-22 17:33:51.205  1490  3658 W WindowManager:         at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1233)
07-22 17:33:51.205  1490  3658 W WindowManager:         at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:394)
07-22 17:33:51.205  1490  3658 W WindowManager:         at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5546)
07-22 17:33:51.205  1490  3658 W WindowManager:         at com.android.server.wm.Transition.finishTransition(Transition.java:1485)
07-22 17:33:51.205  1490  3658 W WindowManager:         at com.android.server.wm.TransitionController.finishTransition(TransitionController.java:1048)
07-22 17:33:51.205  1490  3658 W WindowManager:         at com.android.server.wm.WindowOrganizerController.finishTransition(WindowOrganizerController.java:514)
07-22 17:33:51.205  1490  3658 W WindowManager:         at android.window.IWindowOrganizerController$Stub.onTransact(IWindowOrganizerController.java:270)
07-22 17:33:51.205  1490  3658 W WindowManager:         at com.android.server.wm.WindowOrganizerController.onTransact(WindowOrganizerController.java:230)
07-22 17:33:51.205  1490  3658 W WindowManager:         at android.os.Binder.execTransactInternal(Binder.java:1446)
07-22 17:33:51.205  1490  3658 W WindowManager:         at android.os.Binder.execTransact(Binder.java:1385)
07-22 17:33:51.205  1490  3658 W Process : Unable to open /proc/13538/status
07-22 17:33:51.210  2457  2457 I ImeTracker: system_server:1a1d981c: onShown
07-22 17:33:51.217  2170  2193 V WindowManagerShell: Track 0 became idle
07-22 17:33:51.217  2170  2193 V WindowManagerShell: All active transition animations finished
07-22 17:33:51.224  2457  2457 D RecentsView: onTaskRemoved: 2998, not handling task stack changes
07-22 17:33:51.228  2457  2457 D RecentsView: onTaskRemoved: 2998, not handling task stack changes
07-22 17:33:51.231  1490  2487 W ActivityTaskManager: takeTaskSnapshot: taskId=2998 not found or not visible
07-22 17:33:51.235   595   595 E BpTransactionCompletedListener: Failed to transact (-32)
07-22 17:33:51.236   595   595 E BpTransactionCompletedListener: Failed to transact (-32)
07-22 17:33:51.797  1490  1992 D HintManagerService: Starts cleaning for 10293
07-22 17:33:51.950  2318  2516 D ImpulseConnection: timeout didn't happen: com.google.android.apps.turbo
```

That's all I have for now

**Comment by eseidel** [comment]
You should be able to pull the crash with `adb pull /data/tombstones/tombstone_09 tombstone_09`

**Comment by eseidel** [comment]
I tried it on an old Google Pixel 4 and was not able to get a crash.

**Comment by majusss** [comment]
> I tried it on an old Google Pixel 4 and was not able to get a crash.

I received 3 messages that app crashes from different people with different versions of Android

**Comment by majusss** [comment]
> You should be able to pull the crash with `adb pull /data/tombstones/tombstone_09 tombstone_09`

Give me a second

**Comment by eseidel** [comment]
> > I tried it on an old Google Pixel 4 and was not able to get a crash.
> 
> I received 3 messages that app crashes from different people with different versions of Android

I believe you that it's crashing. :) Just trying to get a repro so I can see the full stack, etc.

**Comment by majusss** [comment]
> > > I tried it on an old Google Pixel 4 and was not able to get a crash.
> > 
> > I received 3 messages that app crashes from different people with different versions of Android
> 
> I believe you that it's crashing. :) Just trying to get a repro so I can see the full stack, etc.

I'm just surprised that it works

**Comment by eseidel** [comment]
My Google Pixel 4 can only go up to Android 13, looks like you're testing with Android 14 on that phone. It may be version-specific.  Although given that you're on Android 14 and seeing a crash it's not 16kb page size related.

**Comment by majusss** [comment]
> My Google Pixel 4 can only go up to Android 13, looks like you're testing with Android 14 on that phone. It may be version-specific.  Although given that you're on Android 14 and seeing a crash it's not 16kb page size related.

Im on A16 beta 2 rn

**Comment by majusss** [comment]
Here you go

[tombstone_09.txt](https://github.com/user-attachments/files/21437213/tombstone_09.txt)

**Comment by eseidel** [comment]
Thanks.  That's helpful.  Unfortunately the stack is still garbage (only 2 frames).  Not sure why.

**Comment by eseidel** [comment]
Note to self, our internal link for this app: https://admin.shorebird.dev/apps/1c384681-654a-428a-a3b2-84b4b0352d13/releases/290479

This was built with the latest Flutter and Shorebird (from last week).  Only non-standard bit is that it was built from linux (which shouldn't matter).

**Comment by majusss** [comment]
Will crashing it again help?

**Comment by eseidel** [comment]
> Will crashing it again help?

Nope.  I just need to figure out how to repro on my machine at this point.

**Comment by majusss** [comment]
> > Will crashing it again help?
> 
> Nope. I just need to figure out how to repro on my machine at this point.

Is there anything I can analyze for you?

**Comment by eseidel** [comment]
@majusss do I have to do anything to make it crash or would you expect it to crash on launch if I'm building my own copy of https://github.com/majusss/purevideo

Does it crash for you within an emulator, or only on a device?

If it does crash within an emulator, can you tell me more about your emulator setup (e.g. what version of android)?

**Comment by eseidel** [comment]
> > > Will crashing it again help?
> > 
> > 
> > Nope. I just need to figure out how to repro on my machine at this point.
> 
> Is there anything I can analyze for you?

We potentially could get on a call and analyze together.  e.g. Discord Video, Google Meet, Zoom, etc.

**Comment by majusss** [comment]
> [@majusss](https://github.com/majusss) do I have to do anything to make it crash or would you expect it to crash on launch if I'm building my own copy of https://github.com/majusss/purevideo
> 
> Does it crash for you within an emulator, or only on a device?
> 
> If it does crash within an emulator, can you tell me more about your emulator setup (e.g. what version of android)?

Yes you need to go to the screen where it initializes media_kit

**Comment by majusss** [comment]
<img width="327" height="99" alt="Image" src="https://github.com/user-attachments/assets/15326ef8-3945-4b01-bcc0-9a68ea2c2eaa" />

From my pixel

**Comment by majusss** [comment]
https://github.com/user-attachments/assets/982981f4-9ded-44ce-b1b6-9b0328d31aeb

From one of my users

**Comment by eseidel** [comment]
Ah!  Then maybe I can get it to crash.  I was just launching the app.  Will poke around more now.

**Comment by eseidel** [comment]
All of the screens are empty for me.  Is there an easy way to get it to init media_kit (e.g. maybe even on launch)?

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/24435c35-0fe5-494e-8b2d-f00755245c3a" />

**Comment by majusss** [comment]
> All of the screens are empty for me. Is there an easy way to get it to init media_kit (e.g. maybe even on launch)?
> 
> <img alt="Image" width="468" height="909" src="https://private-user-images.githubusercontent.com/478541/470980862-0f965d52-a376-4e76-a1fc-be85a292c5b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM0NzY5NjMsIm5iZiI6MTc1MzQ3NjY2MywicGF0aCI6Ii80Nzg1NDEvNDcwOTgwODYyLTBmOTY1ZDUyLWEzNzYtNGU3Ni1hMWZjLWJlODVhMjkyYzViNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyNVQyMDUxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzU0MmIxOWI0MTFiOGY4ZTJlNzQ3MTdmN2EwMDM4YTA3MzEyZWU5ZDNjMjk2YTcxOGIwM2RhNjA4NjdlY2NkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dboP-4jHbf3VR4SWjFuSVoqOb5MulkSaDShialLVS6Y">

Easiest way to access videos is through settings > accounts > "obejrzyj.to" > outlined button

**Comment by eseidel** [comment]
Here?

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/819eac35-6ef4-446c-b7d0-0f4fec621cf7" />

**Comment by majusss** [comment]
Yes, press the second button

**Comment by majusss** [comment]
And go back to home screen

**Comment by eseidel** [comment]
Second button shows me 

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/18244de7-96ac-4c14-b16b-010aacb4a725" />

**Comment by majusss** [comment]
Thats good

**Comment by majusss** [comment]
Now you have access to movies

**Comment by majusss** [comment]
Did you reproduce the crash?

**Comment by eseidel** [comment]
Yes.  I've made a reduction which crashes: https://github.com/eseidel/media_test

**Comment by majusss** [comment]
Nice, I should have done this when reporting this issue

**Comment by eseidel** [comment]
Crashes on Mac too!  With a 500+ deep callstack 😲

**Comment by majusss** [comment]
> Crashes on Mac too!  With a 500+ deep callstack 😲 

I think that on Linux too

**Comment by majusss** [comment]
But I'm done for tonight, I'm going to sleep

**Comment by eseidel** [comment]
I don't think I will end up solving this today, but should be easy to solve on monday or early next week.

**Comment by eseidel** [comment]
Made a little progress this afternoon.  Mostly I've been fighting with XCode.  Flutter Local Engine builds don't seem to play nice with pod files, so I may need to remove the podfile bits from the equation to get it working under a local engine build.

**Comment by majusss** [comment]
How its going? Any progress?

**Comment by eseidel** [comment]
Looking as we speak. :)

**Comment by eseidel** [comment]
https://github.com/eseidel/media_test is no longer crashing for me 🤔 

```
shorebird release android
shorebird preview
```
works just fine now.  I wonder if it's a flutter version issue.

**Comment by eseidel** [comment]
OK, definitely crashes when built with last weeks' 3.32.7:
`shorebird release android --flutter-version=3f14ca5f3bc037b703825519126bbe64aaee1827 --no-confirm`

**Comment by eseidel** [comment]
I wonder if our original 3.32.7 build (which we've since replaced for other reasons) was somehow bad?

**Comment by eseidel** [comment]
At least for me, running with just about any other version of flutter seems to work?  e.g. `shorebird release android` should "just work" now and not crash?

I suspect there is still a bug here, just not able to reproduce it with our latest sources.

**Comment by eseidel** [comment]
I don't see any relevant recent fixes upstream: https://github.com/flutter/flutter/blob/master/CHANGELOG.md

**Comment by eseidel** [comment]
Yeah.  3f14ca5f3bc037b703825519126bbe64aaee1827 fails for Mac too.  But other builds (e.g. 3.32.8) don't.  There must have just been something bad with our dart build on that revision. Really not sure why.

Let me know if you're still seeing this with the latest flutter & shorebird.  Thank you again for the report and sorry for the trouble!

**Comment by eseidel** [comment]
I'm going to assume this is resolved for now.  Please let me know if you see otherwise!  Thank you again for the report!

**Comment by majusss** [comment]
Now it works for me, thanks for all that you do

**Comment by michaldeimert** [comment]
**media_kit + Shorebird: `player.open()` hangs silently (no crash) on Android — Flutter 3.44.0, Shorebird 1.6.x**

I'm hitting a variant of this issue that doesn't crash with SIGBUS but instead **hangs silently**. `player.open()` returns a Future that never completes — no error, no callback, no crash. This only happens in Shorebird-patched builds; standard `flutter build appbundle --release` works perfectly on the same device.

**Environment**
- Shorebird CLI latest (patches deployed via `shorebird patch android`)
- Flutter 3.44.0 (600ed7b04f)
- media_kit 1.2.0, media_kit_video 1.3.0, media_kit_libs_android_video 1.3.9
- Device: Samsung Galaxy S24 Ultra (SM-S928B, arm64, Android 16)
- R8/ProGuard disabled

**What works**
- `libmpv.so` loads successfully (`nativeloader: Load ... libmpv.so ... ok`)
- `MediaKit.ensureInitialized()` completes
- `Player()` and `VideoController()` constructors return fine
- HTTP, platform channels, other async code — all work fine under Shorebird

**What fails**
- `await player.open(Media(url, httpHeaders: headers), play: false)` — the Future never resolves
- No `videoParams` stream events are delivered
- No `error` stream events are delivered
- Timeouts eventually fire, so the app doesn't crash — it just never plays video

**Diagnosis**

Added `print()` statements throughout the init path and deployed via Shorebird patches. Logs confirm:

creating Player url=... creating VideoController url=... player.open url=...

And then silence — no follow-up callbacks ever arrive. The FFI callback path from native libmpv back into Dart appears broken. The `NativeCallable`/`ReceivePort` events that media_kit relies on to deliver mpv events to Dart simply never fire under the patched VM.

This looks like the same fundamental issue (Shorebird's VM modifications breaking FFI callback delivery for media_kit) but manifesting as a silent hang rather than the SIGBUS crash reported originally.

**Comment by bdero** [comment]
@michaldeimert Would you mind giving the latest Flutter 3.44.0 build we just released (dc84dc8c37, pinned as default in 1.6.104) a try? It's expected to resolve some FFI-related issues on both iOS and Android. :)

**Comment by michaldeimert** [comment]
@bdero  Sadly FFI issues still occur and crash the app on Android for media_kit.

**Comment by eseidel** [comment]
Thanks @michaldeimert.  I believe this is the same as https://github.com/shorebirdtech/shorebird/issues/3802, tracking there.
