### ISSUE TITLE
fix: [iOS] incorrect app_id when calling PatchCheckRequest

### ISSUE THREAD

**Issue by aaassseee** [shorebirdtech/shorebird#3277]
App ID: (insert the app_id from your shorebird.yaml here)

**Description**

Releasing iOS to Shorebird upload with correct flavor app_id, however calling PatchCheckRequest with incorrect flavor app_id

dev_gm: 348eb0d9-ba48-4c91-8cb9-819e547da0ab
sit_gm: 19cc2268-104d-4d96-a8f4-e6d2ba19f19a

incorrect

**Steps To Reproduce**

1. release shorebird with command shorebird release ios --no-codesign --flavor=sit_gm --flutter-version=3.27.4
2. patch release with shorebird patch --platforms=ios --flavor=sit_gm --release-version=1.1.4+37
3. check console app log with [shorebird] Sending patch check request: PatchCheckRequest { app_id: "348eb0d9-ba48-4c91-8cb9-819e547da0ab", channel: "stable", release_version: "1.1.4+37", platform: "ios", arch: "aarch64" }

**Expected Behavior**

Sending patch check request should request with 19cc2268-104d-4d96-a8f4-e6d2ba19f19a

**Screenshots**

<img width="1325" height="313" alt="Image" src="https://github.com/user-attachments/assets/74501eca-0b0b-409e-bf79-085b617aed95" />

<img width="1326" height="42" alt="Image" src="https://github.com/user-attachments/assets/c46d221a-1a62-4b6a-9386-bdfc5432a216" />

**Additional Context**

Android works fine. Problem only happened with iOS.

**Comment by bryanoltman** [comment]
Confirmed that the sit_gm flavor of your app has the incorrect app id. Can you share your full shorebird.yaml?

It's also possible this bug has been fixed since Flutter 3.27.4. Are you able to try creating a release with a newer version of Flutter? Ideally 3.32.8, which is the current `stable`.

**Comment by aaassseee** [comment]
@bryanoltman 
```yaml
# This file is used to configure the Shorebird updater used by your app.
# Learn more at https://docs.shorebird.dev
# This file does not contain any sensitive information and should be checked into version control.

# Your app_id is the unique identifier assigned to your app.
# It is used to identify your app when requesting patches from Shorebird's servers.
# It is not a secret and can be shared publicly.
app_id: 348eb0d9-ba48-4c91-8cb9-819e547da0ab
flavors:
  dev_gm: 348eb0d9-ba48-4c91-8cb9-819e547da0ab
  prd_gm: 8aeaa2ff-4f43-43c1-b794-74d5a6a22a85
  sit_gm: 19cc2268-104d-4d96-a8f4-e6d2ba19f19a
  uat_gm: d3c2ea89-6394-4c11-9861-5f510069c3ce
  dev_gm_cn: 90f9a2a1-dc62-4b45-b967-75c31b711427
  prd_gm_cn: 3cf50b7d-3149-4f95-878c-84356456ce85
  sit_gm_cn: ebcef75d-9087-4dea-88e3-77d66f244e7f
  uat_gm_cn: eacc7202-2e34-4e57-9fb4-b3d200079df7

# auto_update controls if Shorebird should automatically update in the background on launch.
# If auto_update: false, you will need to use package:shorebird_code_push to trigger updates.
# https://pub.dev/packages/shorebird_code_push
# Uncomment the following line to disable automatic updates.
auto_update: false
```

> It's also possible this bug has been fixed since Flutter 3.27.4. Are you able to try creating a release with a newer version of Flutter? Ideally 3.32.8, which is the current `stable`.

Maybe not, currently fixed version in 3.27.4.

**Comment by aaassseee** [comment]
@bryanoltman After upgrade Flutter, app_id still incorrect

<img width="1413" height="961" alt="Image" src="https://github.com/user-attachments/assets/4b47b3b9-1cb7-4abf-99b3-c9dc375908a4" />

**Comment by bryanoltman** [comment]
Interesting! Would you mind sharing the log file for this command? `shorebird doctor -v` will print the path to the logs directory (for me, it's `/Users/bryanoltman/Library/Application Support/shorebird/logs`), and the relevant log file will have the unix timestamp of when the command was executed. Alternatively, you can clear that folder, run the command, and there should only be one log file.

**Comment by aaassseee** [comment]
Sure, @bryanoltman . But the log file contains X-Goog-Signature, is it fine to post here?

**Comment by bryanoltman** [comment]
You can email it to contact@shorebird.dev if it contains anything you wouldn't want to post publicly.

**Comment by aaassseee** [comment]
@bryanoltman I have sent the log to contact@shorebird.dev.

**Comment by bryanoltman** [comment]
Received! It looks like the command you're running in the log (`shorebird release ios --no-codesign --flavor=sit_gm --flutter-version=3.27.4 --dart-define-from-file=config/entity/gm.env -- --no-tree-shake-icons`) is uploading the to the correct app ID `19cc2268-104d-4d96-a8f4-e6d2ba19f19a`. However, the artifact's processed shorebird.yaml contains the wrong app id:

```yaml
app_id: 348eb0d9-ba48-4c91-8cb9-819e547da0ab
auto_update: false
```

Can you try running this command with a newer version of Flutter?

**Comment by aaassseee** [comment]
@bryanoltman I have sent the log to [contact@shorebird.dev](mailto:contact@shorebird.dev).

**Comment by bryanoltman** [comment]
Thank you! Looking now

**Comment by bryanoltman** [comment]
Hmm, it appears as though this bug still exists in the latest version of Flutter. Thanks for the report! Digging in now, will post when I have an update.

**Comment by aaassseee** [comment]
@bryanoltman Thanks. I am currently changing the default app_id in shorebird.yaml as work around.

**Comment by bryanoltman** [comment]
Glad to hear there's a workaround. I'm unable to reproduce locally with our sample app at https://github.com/shorebirdtech/samples/tree/main/flavors. I'm running `shorebird release ios --flavor=stable`, where stable is the non-default app id. The xcarchive produced has a shorebird.yaml with the correct app id. Can you run `shorebird doctor -v` and share the output here?

**Comment by aaassseee** [comment]
Sure
```
Shorebird 1.6.56 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.32.8 • revision 6b9522cd0097a8e5c582a0184a80b2cf6ad9ef96
Engine • revision 9f4970613faf7ea8109c9ec23ffd41a02cd2df8b

Logs: /Users/jack.liu/Library/Application Support/shorebird/logs
Android Toolchain
  • Android Studio: not detected
  • Android SDK: /Users/jack.liu/Library/Android/sdk
  • ADB: /Users/jack.liu/Library/Android/sdk/platform-tools/adb
  • JAVA_HOME: not detected
  • JAVA_EXECUTABLE: /usr/bin/java
  • JAVA_VERSION: openjdk version "17.0.15" 2025-04-15 LTS
                  OpenJDK Runtime Environment Corretto-17.0.15.6.1 (build 17.0.15+6-LTS)
                  OpenJDK 64-Bit Server VM Corretto-17.0.15.6.1 (build 17.0.15+6-LTS, mixed mode, sharing)
                  
  • Gradle: 8.0

URL Reachability
✓ https://api.shorebird.dev OK (0.3s)
✓ https://console.shorebird.dev OK (0.6s)
✓ https://oauth2.googleapis.com OK (0.1s)
✓ https://storage.googleapis.com OK (55ms)
✓ https://cdn.shorebird.cloud OK (0.1s)

Network Speed
✓ GCP Upload Speed: 2.68 MB/s (2.2s)
✓ GCP Download Speed: 7.94 MB/s (2.3s)

✓ Shorebird is up-to-date (1.7s)
✓ AndroidManifest.xml files contain INTERNET permission (26ms)
✓ shorebird.yaml found in pubspec.yaml assets (9ms)
✓ Lock files are tracked in source control (85ms)

No issues detected!
```

**Comment by bryanoltman** [comment]
Hmm, that looks fine. If this is working on Android, can you confirm that you have flavors set up in Xcode properly? The steps to do so are at https://docs.flutter.dev/deployment/flavors-ios

**Comment by aaassseee** [comment]
OK let me check deeply. I might also think of Xcode setting. But we have been tested on one day and find without anything is missed.

**Comment by aaassseee** [comment]
@bryanoltman Found what happened, but what made this result is so weird.
My teammate accidently add the FLAVOR field in Xcode user define field, maybe Xcode problem.

<img width="496" height="226" alt="Image" src="https://github.com/user-attachments/assets/de4ed55b-9d77-49e0-91d4-3853b9c85e4a" />

This tiny little change didn't affect any Flutter release or debug, IDK why. But when running shorebird cli release command, it read the empty FLAVOR field. That's why all flavor will fall back to the default app_id.

Just a gust. Maybe shorebird use the value in Xcode setting before Flutter release command ran. So shorebird thinks there is no flavor for this build, but actually after the Flutter release done everything in Flutter backs to normal and build the correct app.

Problem fixed by deleting FLAVOR in user define field. I think this can be improved by checking when flavor is empty but user defined flavor in command.

<img width="1313" height="418" alt="Image" src="https://github.com/user-attachments/assets/bdd09ccf-ae47-4678-9fa8-1380a9a4949f" />

**Comment by bryanoltman** [comment]
Shorebird only uses the flavor to determine an app id (which is why you saw the correct app id in the `shorebird release` logs but not in the patch check code on device) and then forwards it to Flutter. I believe you would've seen this bug using Flutter without Shorebird. As such, I think this check would be more appropriate to implement at the Flutter level than at the Shorebird level. Going to close this issue. I'd recommend opening an issue at https://github.com/flutter/flutter if you'd like to communicate this to the Flutter team.

**Comment by aaassseee** [comment]
@bryanoltman Everything in Flutter works fine with correct flavor. But thanks for the support.
